version: '3.8'

services:
  web:
    image: achmad/fafarasa:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "8832:3000"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge