version: '3.8'

services:
  web:
    image: ramdhanistars/fafarasa:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8832:3000"
    depends_on:
      - db
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root8832
      MARIADB_DATABASE: fafarasa
      MARIADB_USER: fafarasa
      MARIADB_PASSWORD: fafarasa8832
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" # optional, hanya jika mau akses dari luar
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
