services:
  web:
    build: .
    env_file:
      - .env.local
    ports:
      - "8832:3000"
    restart: always
    networks:
      - default
    volumes:
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm start"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge
