version: '3.8'
services:
  web:
    build: .
    environment:
      DATABASE_URL: "mysql://fafarasa:fafarasa@host.docker.internal:3306/fafarasa"
      NODE_ENV: production
    ports:
      - "8832:3000"
    restart: always
    networks:
      - default
    volumes:
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm start"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge 